### ISSUE TITLE
Seed data for ORM

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-api#13]
Add seed data using Sequelize

**Comment by kahboom** [comment]
Setup is complete, but now need to put in more realistic data.

**Comment by gashcrumb** [comment]
@kahboom I imagine this would be blocked until we start defining the required models, right?

**Comment by kahboom** [comment]
@gashcrumb - Yep, which we've started doing. Going to create some dummy data for Connections now. May end up deleting the other models after all just to keep it clean.

**Comment by gashcrumb** [comment]
This has been started and we've some data, wonder when we can call this one closed?

**Comment by kahboom** [comment]
@gashcrumb - I think we have enough for the setup and can add more as needed. Closing this one.
