### ISSUE TITLE
Source env scripts for VM automatically

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-api#14]
## Overview

Add an NPM script to source Minikube automatically prior to running `npm start`. In the near future it would be nice to have this as a configurable option that defaults to Minikube (Kubernetes) when running just `npm start`.
## Reference
- [Make sourcing env scripts configurable](15)

Moved from https://github.com/redhat-ipaas/ipaas-client/issues/44

**Comment by kahboom** [comment]
No longer relevant as Java API is being implemented here: https://github.com/redhat-ipaas/ipaas-api-java
