### ISSUE TITLE
Make sourcing env scripts configurable

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-api#15]
## Overview

Once #44 is completed, you'll be able to run `npm start:minikube` without having to source for Minikube (Kubernetes), or `npm start:minishift` for Minishift (OpenShift), but it would be nice to have it as a completely configurable option, possibly with Minikube as the default value.
## Reference
- [Source VM scripts automatically](14)

Moved from https://github.com/redhat-ipaas/ipaas-client/issues/45

**Comment by kahboom** [comment]
No longer relevant as Java API is being implemented here: https://github.com/redhat-ipaas/ipaas-api-java
