### ISSUE TITLE
Define the `Connection` model

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-api#25]
We've the start of the `Connection` model, but we need to define it more fully in terms of what is required in the UI.

- A connection has a name
- A connection has labels/tags
- A connection has fields that can be visible or not visible

https://issues.jboss.org/projects/IPAAS/issues/IPAAS-87

**Comment by gashcrumb** [comment]
related PR -> https://github.com/redhat-ipaas/ipaas-api/pull/28

**Comment by gashcrumb** [comment]
Gonna track adding some unit tests -> https://github.com/redhat-ipaas/ipaas-api/issues/25

**Comment by kahboom** [comment]
@gashcrumb - Can this be closed?

**Comment by gashcrumb** [comment]
Absolutely!
