### ISSUE TITLE
Attach routes to entities in src/models

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-api#29]
We'll need to expose the various models described in [entities.md](https://github.com/redhat-ipaas/ipaas-api/blob/master/docs/entities.md) starting with Connections and related models.

**Comment by kahboom** [comment]
@gashcrumb - I think this is done, can we close this one out?

**Comment by gashcrumb** [comment]
Yeah, think you got this one sorted...
