### ISSUE TITLE
Missing module breaks deployment

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-api#44]
npm info it worked if it ends with ok
npm info using npm@3.10.8
npm info using node@v6.9.1
npm info lifecycle ipaas-api@1.0.0~prestart: ipaas-api@1.0.0
npm info lifecycle ipaas-api@1.0.0~start: ipaas-api@1.0.0

> ipaas-api@1.0.0 start /usr/src/app
> node server.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/src/app/config/development.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/server.js:16:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm info lifecycle ipaas-api@1.0.0~start: Failed to exec start script
npm ERR! Linux 3.10.0-514.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ipaas-api@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ipaas-api@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ipaas-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ipaas-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ipaas-api
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.10.0-514.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path npm-debug.log.896050243
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.896050243'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.896050243'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.896050243' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

**Comment by kahboom** [comment]
Hey @KurtStam - This is done on purpose as we don't want sensitive information from configuration files to be staged and checked in by Git. The API setup instructions should be to first rename one of the example config files located in `/config`, depending on your environment of choice. For instance, the `config/development-example.json` file should be renamed to `config/development.json` (which is not monitored by Git).

We can of course change this if it's an issue, but figured users may be adding sensitive information like database credentials or possibly just their own preferential settings that someone working off of the same repo may not necessarily want (ie QE).

**Comment by KurtStam** [comment]
Thanks @kahboom, let me see if I can inject that using secrets or configmap on k8s.
