### ISSUE TITLE
‘IntegrationPatternGroup’ should be inside of the JSON for ‘data’

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-api#46]
https://github.com/redhat-ipaas/ipaas-api/blob/master/src/data/fixtures/development.json#L246

‘IntegrationPatternGroup’ should be inside of the JSON for ‘data’, plus it should be called IntegrationPatternGroupId.

**Comment by gashcrumb** [comment]
Damn, copy paste error...

Also sequelize takes care of matching it to the right column, so when we have the proper assocation in place it'll be a json object of the group, not the ID, as the client isn't gonna be able to do anything with the row ID.
