### ISSUE TITLE
small issues in the deployment.json file

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-api#50]
Small naming convention issues, not case and use of "Id"

In Component: ComponentGroup should be componentGroupId
In IntegrationPattern: IntegrationPatternGroup should be integrationPatternGroupId
In Connection: ComponentGroup should be componentId 

For the last one, according to the ERD, the Connection does not have a reference to ComponentGroup (only Component)

**Comment by gashcrumb** [comment]
Working on updating where this data comes from in this PR -> https://github.com/redhat-ipaas/ipaas-api/pull/51

I'll change the association fields in a few
