### ISSUE TITLE
Association model names passed as query params are case-sensitive

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-api#52]
All model names are treated as strings before they are instantiated and can be dropped to lowercase. We can either having a small mapping function that assigns models to the lowercase string (will work, but is kinda hack-y), we can update the models/index.js file to use lowercase strings in some way (probably a breaking, maybe a not-so-good option), or loading associations from BaseRepository.js by first making all model strings lowercase, which might work (not sure).

**Comment by gashcrumb** [comment]
Yeah, going to/from all lowercase to camel case is tricky for sure.

Actually we don't really need a mapping function, we could just build a lookup map when we create the models and then use that.

**Comment by kahboom** [comment]
@gashcrumb - I think we might be talking about the same thing (what I listed as the last option, exception I think it should be done from the BaseRepository file or maybe even BaseService file, not sure).
