### ISSUE TITLE
Cannot run `npm upgrade` due to breaking changes in deps

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-api#53]
We need to upgrade deps one by one, but for now need to use Yarn or NPM's shrinkwrap. Yarn is being used in the new fabric8 UI tech stack, so makes more sense, but NPM shrinkwrap works as well.

**Comment by gashcrumb** [comment]
No I hit this issue in ipaas-client and raised it -> https://github.com/redhat-ipaas/ipaas-client/issues/73

**Comment by gashcrumb** [comment]
But we probably should start using yarn btw :-) for sure

**Comment by kahboom** [comment]
Ahh lol nvm then, closing this.
